server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        try_files $uri $uri/ /index.html;
    }

    location /config/ {
        alias /config/;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /css/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location /js/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location = /proxy {
        proxy_pass http://127.0.0.1:8888/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
    }
}
