apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "webportal.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "webportal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webportal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: webportal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          {{- if .Values.persistence.config.enabled }}
          hostPath:
            path: {{ .Values.persistence.config.hostPath }}
            type: DirectoryOrCreate
          {{- else emptyDir: {} }}
          {{- end }}
